### ISSUE TITLE
Problem using as Alire crate

### ISSUE THREAD

**Issue by SMerrony** [AdaCore/win32ada#5]
When I try to alr build with the package withed in the normal way into a project I get a load of error messages shown below...

```win32-winnt.ads:1495:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:1539:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:1660:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:1722:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:1724:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:1726:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2059:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2062:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2064:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2079:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2084:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2089:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2404:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2408:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2412:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2457:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2465:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2473:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2476:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2481:01: error: preprocessor directive ignored, preprocessor not active
win32-winnt.ads:2486:01: error: preprocessor directive ignored, preprocessor not active
```

It seems that adding `,"-gnateDTARGET=Win32"` to the Alire-generated `.gpr` file works around the problem,
but that's not a solution that I can deploy in an Alire crate.

**Comment by Fabien-Chouteau** [comment]
Hello @SMerrony , which Alire-generated .gpr are you referring to here? The win32ada crate is not using Alire-generated project files.

**Comment by SMerrony** [comment]
Hi @Fabien-Chouteau, 

I'm referring to the projectname_config.gpr that Alire automatically creates in the `config` directory (that it also creates) when I try to `alr build` my project that has win32ada `with`ed.

I just did a clean build to verify; I deleted the `alire`, `config`, and `obj` directories, then did an `alr build`.
As I expected, Alire recreated those three directories and also projectname_config.ads, projectname_config.gpr, and projectname_config.h in the `config` directory.

The source code is here on Github https://github.com/SMerrony/emdee.

**Comment by Fabien-Chouteau** [comment]
I see what is going on. You indeed have to set `-gnateDTARGET=Win32` or `-gnateDTARGET=Win64` compiler switches because Alire is not doing a build and install of the library but rather uses sources directly.

However, you don't have to put this switch in the `config/<projectname>_config.gpr` project file. You can do it in `<projectname>.gpr`:
```
package Compiler is
      for Default_Switches ("Ada") use <projectname>_Config.Ada_Compiler_Switches & ("-gnateDTARGET=Win32");
end Compiler;
```
or
```
package Compiler is
      for Default_Switches ("Ada") use <projectname>_Config.Ada_Compiler_Switches & ("-gnateDTARGET=Win64");
end Compiler;
```

**Comment by SMerrony** [comment]
Thanks @Fabien-Chouteau - that works.

I've changed the project.gpr file as follows so that the project builds under Linux and Windows...
```
   package Compiler is
      case Emdee_Config.Alire_Host_Os is
         when "windows" =>
            for Default_Switches ("Ada") use Emdee_Config.Ada_Compiler_Switches & ("-gnateDTARGET=Win64");
         when others =>
            for Default_Switches ("Ada") use Emdee_Config.Ada_Compiler_Switches;
      end case;
   end Compiler;
```
Could this be documented somewhere?  Ideally on the win32ada crate landing page, otherwise on the GitHub project page (which currently has no mention of Alire).
